### ISSUE TITLE
:after, :before pseudo clear attributes on "row" classes?

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [ummahusla/PotatoCSS#52]
Should the use of the following, for example, be implemented?

``` css
.row:before,
.row:after {
    display: table;
    clear: both;
    content: "";
}
```
