### ISSUE TITLE
Add utility classes examples

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#79]
At the moment, **PotatoCSS** has next utility classes: 

```css
.text-center { text-align: center; }
.text-right { text-align: right; }
.text-left { text-align: left; }
.text-justify { text-align: justify; }
.float-left { float: left; }
.float-right { float: right; }
.font-light { font-weight: lighter; }
.font-normal { font-weight: normal; }
.font-bold { font-weight: bold; }
```
